version: '3.8'

services:
  api:
    image: halissonbrancalhao/bytebank-api:latest
    container_name: bytebank
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/bytebank
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    container_name: bytebank_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
